source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'Pasha' do
    pod 'Alamofire', '~> 3.4'
    pod 'SWXMLHash', '~> 2.3.0'
    pod 'AlamofireImage', '~> 2.0'

end
